name: Pylint

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [ "main" ]

env:
  PYLINT_THRESHOLD: 9.5

jobs:
  run-pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Run pylint
      run: |
        python -m pip install pylint
        python -m pylint --fail-under ${{env.PYLINT_THRESHOLD}} $(git ls-files '*.py')

