name: Tests

on:
  push:
    branches: ["*"]

env:
  PYLINT_THRESHOLD: 9.5

jobs:
  main-workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Find and replace PAT_SECRET
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: "$REPLACE_WITH_PAT"
        replace: ${{secrets.PAT_SECRET}}
        regex: false
    
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Install dependencies
      run: |
        poetry install --no-interaction

    - name: Run pylint
      run: |
        python -m pip install pylint
        python -m pylint --fail-under ${{env.PYLINT_THRESHOLD}} $(git ls-files '*.py')

    - name: Run tests and create coverage badge
      run: |
        source .venv/bin/activate
        pytest --cov=gh_env_manager tests >> temp.txt
        cat temp.txt
        cat temp.txt | grep 'TOTAL' | grep  -E -i -o '([0-9]+)%' | python .github/badges/badgecreator.py

    - name: Commit coverage badge
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'chore: update coverage badge'
        add: '*.svg'

    - name: Dry-run publish
      run: |
        poetry publish --build --no-interaction --dry-run
