name: Update badges

on:
  push:
    branches: ["*"]

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9' 
        cache: 'pip' # caching pip dependencies

    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies
      run: poetry install --no-interaction

    - name: Run tests and create coverage badge
      run: |
        pytest --cov tests
        pytest --cov tests | grep 'TOTAL' | grep  -E -i -o '([0-9]+)%'
        python badges/badgecreator.py

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'chore: update coverage badge'
        add: '*.svg'
      
