name: Update badges

on:
  push:
    branches: ["*"]

jobs:
  test-create-badges-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        #cache: 'pip' # caching pip dependencies

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Install dependencies
      run: poetry install --no-interaction

    - name: Run tests and create coverage badge
      run: |
        source .venv/bin/activate
        pytest --cov=gh_env_manager tests
        pytest --cov=gh_env_manager tests | grep 'TOTAL' | grep  -E -i -o '([0-9]+)%'
        python badges/badgecreator.py

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'chore: update coverage badge'
        add: '*.svg'
    
    # - name: Build and publish
    #   run: |
    #     poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
    #     poetry publish --build --no-interaction
